version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - webnet

  frontend:
    build: ./frontend
    networks:
      - webnet

  reverse-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

